services:
  web:
    # platform: linux/amd64 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting_manager_web
    command: flask --app app/app.py run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: meeting_manager_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meetingdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
